class Character {
  final String? id; // Firestore document ID
  final String playerName;
  final String characterName;
  final int characterNumber;
  final String race;
  final Build build;
  final Map<String, dynamic> affinityPoints;
  final Map<String, dynamic> hitPoints; 
  final Map<String, dynamic> dr;
  final String cultivationTier;
  final List<Skill> skills;
  final Map<String, AffinityDetail> affinities;
  final String? generatedAt; // When the pc.json was last generated by App Script
  final String? playerUid; // Firebase Auth UID for verification

  Character({
    this.id,
    required this.playerName,
    required this.characterName,
    required this.characterNumber,
    required this.race,
    required this.build,
    required this.affinityPoints,
    required this.hitPoints,
    required this.dr,
    required this.cultivationTier,
    required this.skills,
    required this.affinities,
    this.generatedAt,
    this.playerUid,
  });

  int get totalAffinityPoints => (affinityPoints['Total Affinity Points'] ?? affinityPoints['affinityPointsTotal'] ?? 0) as int;
  int get unspentAffinityPoints => (affinityPoints['unspent'] ?? affinityPoints['affinityTierPointUnspent'] ?? 0) as int;
  int get perfectCultivationPoints => (affinityPoints['Perfect Cultivation Points'] ?? 0) as int;

  factory Character.fromJson(Map<String, dynamic> json, {String? id}) {
    final dynamic rawNumber = json['characterNumber'];
    int parsedNumber = 0;
    if (rawNumber is int) {
      parsedNumber = rawNumber;
    } else if (rawNumber is String) {
      parsedNumber = int.tryParse(rawNumber) ?? 0;
    }

    final Map<String, dynamic> rawBuild = (json['build'] is Map<String, dynamic>)
        ? Map<String, dynamic>.from(json['build'])
        : <String, dynamic>{};
    final Map<String, dynamic> rawHitPoints = (json['hitPoints'] is Map<String, dynamic>)
        ? Map<String, dynamic>.from(json['hitPoints'])
        : <String, dynamic>{};
    final Map<String, dynamic> rawAffinities = (json['affinities'] is Map<String, dynamic>)
        ? Map<String, dynamic>.from(json['affinities'])
        : <String, dynamic>{};
    final Map<String, dynamic> rawAffinityPoints = (json['affinityPoints'] is Map<String, dynamic>)
        ? Map<String, dynamic>.from(json['affinityPoints'])
        : <String, dynamic>{};
    final List<dynamic> rawSkills = (json['skills'] is List)
        ? (json['skills'] as List<dynamic>)
        : <dynamic>[];

    return Character(
      id: id ?? (json['id']?.toString()),
      playerName: (json['playerName'] ?? 'Unknown') as String,
      characterName: (json['characterName'] ?? 'Unknown') as String,
      characterNumber: parsedNumber,
      race: (json['race'] ?? 'Unknown') as String,
      build: Build.fromJson(rawBuild),
      dr: Map<String, dynamic>.from(json['dr'] ?? {}),
      affinityPoints: rawAffinityPoints,
      hitPoints: rawHitPoints,
      cultivationTier: (json['cultivationTier'] ?? 'Unknown') as String,
      skills: rawSkills
          .whereType<Map<String, dynamic>>()
          .map((skill) => Skill.fromJson(skill))
          .toList(),
      affinities: rawAffinities.map(
        (key, value) => MapEntry(
          key,
          value is Map<String, dynamic>
              ? AffinityDetail.fromJson(value)
              : AffinityDetail.fromJson(<String, dynamic>{'effectLevel': 0}),
        ),
      ),
      generatedAt: json['generatedAt'] as String?,
      playerUid: json['playerUid'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'playerName': playerName,
      'characterName': characterName,
      'characterNumber': characterNumber,
      'race': race,
      'build': build.toJson(),
      'dr': dr,
      'affinityPoints': affinityPoints,
      'hitPoints': hitPoints,
      'cultivationTier': cultivationTier,
      'skills': skills.map((skill) => skill.toJson()).toList(),
      'affinities': affinities.map((key, value) => MapEntry(key, value.toJson())),
      if (generatedAt != null) 'generatedAt': generatedAt,
      if (playerUid != null) 'playerUid': playerUid,
    };
  }

}

class Skill {
  final String name;
  final String type;
  final int level;
  final String frequency;
  final String? verbal;
  final String? description;
  final String? delivery;

  Skill({
    required this.name,
    required this.type,
    required this.level,
    required this.frequency,
    this.verbal,
    this.description,
    this.delivery,
  });

  factory Skill.fromJson(Map<String, dynamic> json) {
    return Skill(
      name: (json['name'] ?? 'Unknown') as String,
      type: (json['type'] ?? 'Common') as String,
      level: (json['level'] is num) ? (json['level'] as num).toInt() : 0,
      frequency: (json['frequency'] ?? 'Passive') as String,
      verbal: json['verbal'] as String?,
      description: json['description'] as String?,
      delivery: json['delivery'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'type': type,
      'level': level,
      'frequency': frequency,
      if (verbal != null) 'verbal': verbal,
      if (description != null) 'description': description,
      if (delivery != null) 'delivery': delivery,
    };
  }
}


class AffinityDetail {
  final int effectLevel;
  final Map<String, int> tiers;

  AffinityDetail({required this.effectLevel, required this.tiers});

  factory AffinityDetail.fromJson(Map<String, dynamic> json) {
    final tiers = <String, int>{};

    for (final key in json.keys) {
      if (key != 'effectLevel') {
        tiers[key] = json[key];
      }
    }

    return AffinityDetail(
      effectLevel: json['effectLevel'],
      tiers: tiers,
    );
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{
      'effectLevel': effectLevel,
    };
    json.addAll(tiers);
    return json;
  }
}

class Build {
  final int total;
  final int unspent;
  final int needToAscend;
  final StartingBuild starting;
  final List<BuildGain> gains;

  Build({
    required this.total,
    required this.unspent,
    required this.needToAscend,
    required this.starting,
    required this.gains,
  });

  factory Build.fromJson(Map<String, dynamic> json) {
    final Map<String, dynamic> raw = json;
    final Map<String, dynamic> rawStarting = (raw['starting'] is Map<String, dynamic>)
        ? Map<String, dynamic>.from(raw['starting'])
        : <String, dynamic>{};
    final List<dynamic> rawGains = (raw['gains'] is List)
        ? (raw['gains'] as List<dynamic>)
        : <dynamic>[];
    return Build(
      total: (raw['total'] is num) ? (raw['total'] as num).toInt() : 0,
      unspent: (raw['unspent'] is num) ? (raw['unspent'] as num).toInt() : 0,
      needToAscend: (raw['needToAscend'] is num) ? (raw['needToAscend'] as num).toInt() : 0,
      starting: StartingBuild.fromJson(rawStarting),
      gains: rawGains
          .whereType<Map<String, dynamic>>()
          .map((gain) => BuildGain.fromJson(gain))
          .toList(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'total': total,
      'unspent': unspent,
      'needToAscend': needToAscend,
      'starting': starting.toJson(),
      'gains': gains.map((gain) => gain.toJson()).toList(),
    };
  }
}


class StartingBuild {
  final int amount;
  final String date;

  StartingBuild({required this.amount, required this.date});

  factory StartingBuild.fromJson(Map<String, dynamic> json) {
    final Map<String, dynamic> raw = json;
    return StartingBuild(
      amount: (raw['amount'] is num) ? (raw['amount'] as num).toInt() : 0,
      date: (raw['date'] ?? '') as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'amount': amount,
      'date': date,
    };
  }
}

class BuildGain {
  final int amount;
  final String reason;
  final String note;
  final String date;

  BuildGain({
    required this.amount,
    required this.reason,
    required this.note,
    required this.date,
  });

  factory BuildGain.fromJson(Map<String, dynamic> json) {
    return BuildGain(
      amount: (json['amount'] is num) ? (json['amount'] as num).toInt() : 0,
      reason: (json['reason'] ?? '') as String,
      note: (json['note'] ?? '') as String,
      date: (json['date'] ?? '') as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'amount': amount,
      'reason': reason,
      'note': note,
      'date': date,
    };
  }
}