// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6pJb56UjgUI2Pk5fFoHYTazY843Xciho',
    appId: '1:999937639575:web:266479fe5ae4dbc2f2d5d2',
    messagingSenderId: '999937639575',
    projectId: 'crucible-helper',
    authDomain: 'crucible-helper.firebaseapp.com',
    storageBucket: 'crucible-helper.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_7E8uzMu9Qm-Jynx8iys7dud3I2I00Rk',
    appId: '1:999937639575:android:bb7540584cd638ecf2d5d2',
    messagingSenderId: '999937639575',
    projectId: 'crucible-helper',
    storageBucket: 'crucible-helper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5yVRNJ8TNihqjxN0Fxysqkzq666LfhN0',
    appId: '1:999937639575:ios:a2d47d0ec7dee32ff2d5d2',
    messagingSenderId: '999937639575',
    projectId: 'crucible-helper',
    storageBucket: 'crucible-helper.firebasestorage.app',
    iosBundleId: 'com.example.crucibleHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5yVRNJ8TNihqjxN0Fxysqkzq666LfhN0',
    appId: '1:999937639575:ios:a2d47d0ec7dee32ff2d5d2',
    messagingSenderId: '999937639575',
    projectId: 'crucible-helper',
    storageBucket: 'crucible-helper.firebasestorage.app',
    iosBundleId: 'com.example.crucibleHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6pJb56UjgUI2Pk5fFoHYTazY843Xciho',
    appId: '1:999937639575:web:48a9b5296da2f7cef2d5d2',
    messagingSenderId: '999937639575',
    projectId: 'crucible-helper',
    authDomain: 'crucible-helper.firebaseapp.com',
    storageBucket: 'crucible-helper.firebasestorage.app',
  );
}
